# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arpanbhandari/Documents/coding/ziply

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arpanbhandari/Documents/coding/ziply

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arpanbhandari/Documents/coding/ziply/CMakeFiles /Users/arpanbhandari/Documents/coding/ziply//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arpanbhandari/Documents/coding/ziply/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ziply

# Build rule for target.
ziply: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ziply
.PHONY : ziply

# fast build rule for target.
ziply/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/build
.PHONY : ziply/fast

src/error.o: src/error.cpp.o
.PHONY : src/error.o

# target to build an object file
src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/error.cpp.o
.PHONY : src/error.cpp.o

src/error.i: src/error.cpp.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/file.o: src/file.cpp.o
.PHONY : src/file.o

# target to build an object file
src/file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/file.cpp.o
.PHONY : src/file.cpp.o

src/file.i: src/file.cpp.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/file.cpp.i
.PHONY : src/file.cpp.i

src/file.s: src/file.cpp.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/file.cpp.s
.PHONY : src/file.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/stb_image_write.o: src/stb_image_write.cpp.o
.PHONY : src/stb_image_write.o

# target to build an object file
src/stb_image_write.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/stb_image_write.cpp.o
.PHONY : src/stb_image_write.cpp.o

src/stb_image_write.i: src/stb_image_write.cpp.i
.PHONY : src/stb_image_write.i

# target to preprocess a source file
src/stb_image_write.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/stb_image_write.cpp.i
.PHONY : src/stb_image_write.cpp.i

src/stb_image_write.s: src/stb_image_write.cpp.s
.PHONY : src/stb_image_write.s

# target to generate assembly for a file
src/stb_image_write.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/stb_image_write.cpp.s
.PHONY : src/stb_image_write.cpp.s

src/threadPool.o: src/threadPool.cpp.o
.PHONY : src/threadPool.o

# target to build an object file
src/threadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/threadPool.cpp.o
.PHONY : src/threadPool.cpp.o

src/threadPool.i: src/threadPool.cpp.i
.PHONY : src/threadPool.i

# target to preprocess a source file
src/threadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/threadPool.cpp.i
.PHONY : src/threadPool.cpp.i

src/threadPool.s: src/threadPool.cpp.s
.PHONY : src/threadPool.s

# target to generate assembly for a file
src/threadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/threadPool.cpp.s
.PHONY : src/threadPool.cpp.s

src/ziply.o: src/ziply.cpp.o
.PHONY : src/ziply.o

# target to build an object file
src/ziply.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/ziply.cpp.o
.PHONY : src/ziply.cpp.o

src/ziply.i: src/ziply.cpp.i
.PHONY : src/ziply.i

# target to preprocess a source file
src/ziply.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/ziply.cpp.i
.PHONY : src/ziply.cpp.i

src/ziply.s: src/ziply.cpp.s
.PHONY : src/ziply.s

# target to generate assembly for a file
src/ziply.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ziply.dir/build.make CMakeFiles/ziply.dir/src/ziply.cpp.s
.PHONY : src/ziply.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ziply"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/stb_image_write.o"
	@echo "... src/stb_image_write.i"
	@echo "... src/stb_image_write.s"
	@echo "... src/threadPool.o"
	@echo "... src/threadPool.i"
	@echo "... src/threadPool.s"
	@echo "... src/ziply.o"
	@echo "... src/ziply.i"
	@echo "... src/ziply.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

